name:                envelopes
version:             1.0.0.0
author:              Author name here
maintainer:          example@example.com
copyright:           "MIT"

dependencies:
  - base
  - optparse-applicative == 0.17.0.0

library:
  source-dirs: src

executables:
  envelopes:
    main:                Main.hs
    source-dirs:         app/envelopes
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - envelopes
